package com.example.visapenaltyfeecalculation.dto;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
public class CountryDto {

    private int id;
    private String countryGroup;
    private String country;
    private int visaDuration;
    private BigDecimal firstMonthPenaltyAmount;
    private BigDecimal monthlyPenaltyAmount;
    private BigDecimal cardFee;
    private BigDecimal visaFee;

    public int getId() {
        return id;
    }

    public CountryDto setId(int id) {
        this.id = id;
        return this;
    }

    public String getCountryGroup() {
        return countryGroup;
    }

    public CountryDto setCountryGroup(String countryGroup) {
        this.countryGroup = countryGroup;
        return this;
    }

    public String getCountry() {
        return country;
    }

    public CountryDto setCountry(String country) {
        this.country = country;
        return this;
    }

    public int getVisaDuration() {
        return visaDuration;
    }

    public CountryDto setVisaDuration(int visaDuration) {
        this.visaDuration = visaDuration;
        return this;
    }

    public BigDecimal getFirstMonthPenaltyAmount() {
        return firstMonthPenaltyAmount;
    }

    public CountryDto setFirstMonthPenaltyAmount(BigDecimal firstMonthPenaltyAmount) {
        this.firstMonthPenaltyAmount = firstMonthPenaltyAmount;
        return this;
    }

    public BigDecimal getMonthlyPenaltyAmount() {
        return monthlyPenaltyAmount;
    }

    public CountryDto setMonthlyPenaltyAmount(BigDecimal monthlyPenaltyAmount) {
        this.monthlyPenaltyAmount = monthlyPenaltyAmount;
        return this;
    }

    public BigDecimal getCardFee() {
        return cardFee;
    }

    public CountryDto setCardFee(BigDecimal cardFee) {
        this.cardFee = cardFee;
        return this;
    }

    public BigDecimal getVisaFee() {
        return visaFee;
    }

    public CountryDto setVisaFee(BigDecimal visaFee) {
        this.visaFee = visaFee;
        return this;
    }

    @Override
    public String toString() {
        return "CountryDto{" +
                "id=" + id +
                ", countryGroup='" + countryGroup + '\'' +
                ", country='" + country + '\'' +
                ", visaDuration=" + visaDuration +
                ", firstMonthPenaltyAmount=" + firstMonthPenaltyAmount +
                ", monthlyPenaltyAmount=" + monthlyPenaltyAmount +
                ", cardFee=" + cardFee +
                ", visaFee=" + visaFee +
                '}';
    }

    public static List<CountryDto> countriesList() {
        List<CountryDto> list = new ArrayList<>();
        list.add(new CountryDto()
                .setId(1)
                .setCountryGroup("A")
                .setCountry("Afganistan")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(2)
                .setCountryGroup("A")
                .setCountry("Almanya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(3)
                .setCountryGroup("A")
                .setCountry("Amerika Birleşik Devletleri")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(4)
                .setCountryGroup("A")
                .setCountry("Andora")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(5)
                .setCountryGroup("A")
                .setCountry("Angola")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(6)
                .setCountryGroup("A")
                .setCountry("Antigua-Barbuda")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(7)
                .setCountryGroup("A")
                .setCountry("Arjantin")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(8)
                .setCountryGroup("A")
                .setCountry("Avustralya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(9)
                .setCountryGroup("A")
                .setCountry("Avusturya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(10)
                .setCountryGroup("A")
                .setCountry("Azerbaycan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(11)
                .setCountryGroup("A")
                .setCountry("Bahama")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(12)
                .setCountryGroup("A")
                .setCountry("Bahreyn")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(13)
                .setCountryGroup("A")
                .setCountry("Bangladeş")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(14)
                .setCountryGroup("A")
                .setCountry("Barbados")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(15)
                .setCountryGroup("A")
                .setCountry("Belize")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(16)
                .setCountryGroup("A")
                .setCountry("Benin")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(17)
                .setCountryGroup("A")
                .setCountry("Bhutan")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(18)
                .setCountryGroup("A")
                .setCountry("Birleşik Arap Emirlikleri")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(19)
                .setCountryGroup("A")
                .setCountry("Bolivya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(20)
                .setCountryGroup("A")
                .setCountry("Bosna Hersek")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(21)
                .setCountryGroup("A")
                .setCountry("Bostwana")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(22)
                .setCountryGroup("A")
                .setCountry("Brezilya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(23)
                .setCountryGroup("A")
                .setCountry("Brunei")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(24)
                .setCountryGroup("A")
                .setCountry("Bulgaristan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(25)
                .setCountryGroup("A")
                .setCountry("Burkina Faso")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(26)
                .setCountryGroup("A")
                .setCountry("Burundi")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(27)
                .setCountryGroup("A")
                .setCountry("Cape Verde")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(28)
                .setCountryGroup("A")
                .setCountry("Cibuti")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(29)
                .setCountryGroup("A")
                .setCountry("Cook Adaları")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(30)
                .setCountryGroup("A")
                .setCountry("Çad")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(31)
                .setCountryGroup("A")
                .setCountry("Çin Halk Cumhuriyeti")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(32)
                .setCountryGroup("A")
                .setCountry("Doğu Timor")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(33)
                .setCountryGroup("A")
                .setCountry("Dominik")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(34)
                .setCountryGroup("A")
                .setCountry("Dominika")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(35)
                .setCountryGroup("A")
                .setCountry("Ekvator")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(36)
                .setCountryGroup("A")
                .setCountry("Ekvator Ginesi")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(37)
                .setCountryGroup("A")
                .setCountry("El Salvador")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(38)
                .setCountryGroup("A")
                .setCountry("Endonezya")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(39)
                .setCountryGroup("A")
                .setCountry("Eritre")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(40)
                .setCountryGroup("A")
                .setCountry("Ermenistan")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(41)
                .setCountryGroup("A")
                .setCountry("Estonya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(42)
                .setCountryGroup("A")
                .setCountry("Filistin")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(43)
                .setCountryGroup("A")
                .setCountry("Finlandiya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(44)
                .setCountryGroup("A")
                .setCountry("Fransa")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(45)
                .setCountryGroup("A")
                .setCountry("Gabon")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(46)
                .setCountryGroup("A")
                .setCountry("Gambiya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(47)
                .setCountryGroup("A")
                .setCountry("Gana")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(48)
                .setCountryGroup("A")
                .setCountry("Gine")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(49)
                .setCountryGroup("A")
                .setCountry("Gine-Bissau")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(50)
                .setCountryGroup("A")
                .setCountry("Grenada")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(51)
                .setCountryGroup("A")
                .setCountry("Guatemala")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(52)
                .setCountryGroup("A")
                .setCountry("Guyana")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(53)
                .setCountryGroup("A")
                .setCountry("Güney Afrika")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(54)
                .setCountryGroup("A")
                .setCountry("Güney Kıbrıs Rum Kesimi")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(55)
                .setCountryGroup("A")
                .setCountry("Gürcistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(56)
                .setCountryGroup("A")
                .setCountry("Haiti")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(57)
                .setCountryGroup("A")
                .setCountry("Hırvatistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(58)
                .setCountryGroup("A")
                .setCountry("Hindistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(59)
                .setCountryGroup("A")
                .setCountry("Hollanda")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(60)
                .setCountryGroup("A")
                .setCountry("Honduras")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(61)
                .setCountryGroup("A")
                .setCountry("İngiltere")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(62)
                .setCountryGroup("A")
                .setCountry("İran")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(63)
                .setCountryGroup("A")
                .setCountry("İsveç")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(64)
                .setCountryGroup("A")
                .setCountry("İsviçre")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(65)
                .setCountryGroup("A")
                .setCountry("İtalya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(66)
                .setCountryGroup("A")
                .setCountry("İzlanda")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(67)
                .setCountryGroup("A")
                .setCountry("Jamaika")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(68)
                .setCountryGroup("A")
                .setCountry("Kamerun")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(69)
                .setCountryGroup("A")
                .setCountry("Kanada")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(70)
                .setCountryGroup("A")
                .setCountry("Katar")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(71)
                .setCountryGroup("A")
                .setCountry("Kazakistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(72)
                .setCountryGroup("A")
                .setCountry("Kenya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(73)
                .setCountryGroup("A")
                .setCountry("Kırgizstan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(74)
                .setCountryGroup("A")
                .setCountry("Kiribati")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(75)
                .setCountryGroup("A")
                .setCountry("Kolombiya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(76)
                .setCountryGroup("A")
                .setCountry("Komorlar Birliği")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(77)
                .setCountryGroup("A")
                .setCountry("Kongo")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(78)
                .setCountryGroup("A")
                .setCountry("Kuzey Kore")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(79)
                .setCountryGroup("A")
                .setCountry("Kosta Rika")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(80)
                .setCountryGroup("A")
                .setCountry("Kuzey Kıbrıs Türk Cum")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(81)
                .setCountryGroup("A")
                .setCountry("Küba")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(82)
                .setCountryGroup("A")
                .setCountry("Laos")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(83)
                .setCountryGroup("A")
                .setCountry("Lesotho")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(84)
                .setCountryGroup("A")
                .setCountry("Letonya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(85)
                .setCountryGroup("A")
                .setCountry("Liberya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(86)
                .setCountryGroup("A")
                .setCountry("Libya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(87)
                .setCountryGroup("A")
                .setCountry("Lihtenştayn")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(88)
                .setCountryGroup("A")
                .setCountry("Litvanya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(89)
                .setCountryGroup("A")
                .setCountry("Lübnana")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(90)
                .setCountryGroup("A")
                .setCountry("Macaristan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(91)
                .setCountryGroup("A")
                .setCountry("Madagaskar(Malagazi)")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(92)
                .setCountryGroup("A")
                .setCountry("Malavi")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(93)
                .setCountryGroup("A")
                .setCountry("Maldivler")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(94)
                .setCountryGroup("A")
                .setCountry("Malezya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(95)
                .setCountryGroup("A")
                .setCountry("Marshall Adaları")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(96)
                .setCountryGroup("A")
                .setCountry("Mauritius")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(97)
                .setCountryGroup("A")
                .setCountry("Meksika")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(98)
                .setCountryGroup("A")
                .setCountry("Moğolistan")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(99)
                .setCountryGroup("A")
                .setCountry("Moldova")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(100)
                .setCountryGroup("A")
                .setCountry("Monako")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(101)
                .setCountryGroup("A")
                .setCountry("Moritanya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(102)
                .setCountryGroup("A")
                .setCountry("Mozombik")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(103)
                .setCountryGroup("A")
                .setCountry("Myanmar(Burma,Birmanya)")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(104)
                .setCountryGroup("A")
                .setCountry("Namibya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(105)
                .setCountryGroup("A")
                .setCountry("Nauru")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(106)
                .setCountryGroup("A")
                .setCountry("Nijer")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(107)
                .setCountryGroup("A")
                .setCountry("Nijerya")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(108)
                .setCountryGroup("A")
                .setCountry("Nikaragua")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(109)
                .setCountryGroup("A")
                .setCountry("Orta Afrika Cumhuriyeti")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(110)
                .setCountryGroup("A")
                .setCountry("Özbekistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(111)
                .setCountryGroup("A")
                .setCountry("Pakistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(112)
                .setCountryGroup("A")
                .setCountry("Palau")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(113)
                .setCountryGroup("A")
                .setCountry("Panama")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(114)
                .setCountryGroup("A")
                .setCountry("Papua Yeni Gine")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(115)
                .setCountryGroup("A")
                .setCountry("Paraguay")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(116)
                .setCountryGroup("A")
                .setCountry("Peru")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(117)
                .setCountryGroup("A")
                .setCountry("Polonya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(118)
                .setCountryGroup("A")
                .setCountry("Portekiz")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(119)
                .setCountryGroup("A")
                .setCountry("Romanya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(120)
                .setCountryGroup("A")
                .setCountry("Ruanda")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(121)
                .setCountryGroup("A")
                .setCountry("Samoa")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(122)
                .setCountryGroup("A")
                .setCountry("San Marino")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(123)
                .setCountryGroup("A")
                .setCountry("Sao Tome ve Principe")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(124)
                .setCountryGroup("A")
                .setCountry("Senegal")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(125)
                .setCountryGroup("A")
                .setCountry("Seyşeller")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(126)
                .setCountryGroup("A")
                .setCountry("Sierra Leone")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(127)
                .setCountryGroup("A")
                .setCountry("Slovakya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(128)
                .setCountryGroup("A")
                .setCountry("Slovenya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(129)
                .setCountryGroup("A")
                .setCountry("Solomon Adaları")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(130)
                .setCountryGroup("A")
                .setCountry("Somali")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(131)
                .setCountryGroup("A")
                .setCountry("St.Kitts ve Nevis")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(132)
                .setCountryGroup("A")
                .setCountry("St.Lucia")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(133)
                .setCountryGroup("A")
                .setCountry("St.Vincent ve Grenagines")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(134)
                .setCountryGroup("A")
                .setCountry("Sudan")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(135)
                .setCountryGroup("A")
                .setCountry("Surinam")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(136)
                .setCountryGroup("A")
                .setCountry("Suudi Arabistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(137)
                .setCountryGroup("A")
                .setCountry("Swaziland")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(138)
                .setCountryGroup("A")
                .setCountry("Şili")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(139)
                .setCountryGroup("A")
                .setCountry("Tanzanya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(140)
                .setCountryGroup("A")
                .setCountry("Tayland")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(141)
                .setCountryGroup("A")
                .setCountry("Togo")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(142)
                .setCountryGroup("A")
                .setCountry("Tonga")
                .setVisaDuration(0)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(143)
                .setCountryGroup("A")
                .setCountry("Trinidad-Tobago")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(144)
                .setCountryGroup("A")
                .setCountry("Tuvalu")
                .setVisaDuration(0)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(145)
                .setCountryGroup("A")
                .setCountry("Uganda")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(146)
                .setCountryGroup("A")
                .setCountry("Ukrayna")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(147)
                .setCountryGroup("A")
                .setCountry("Uruguay")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(148)
                .setCountryGroup("A")
                .setCountry("Vanuatu")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(149)
                .setCountryGroup("A")
                .setCountry("Vatikan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(150)
                .setCountryGroup("A")
                .setCountry("Venezuela")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(151)
                .setCountryGroup("A")
                .setCountry("Vietnam")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(152)
                .setCountryGroup("A")
                .setCountry("Yemen")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(153)
                .setCountryGroup("A")
                .setCountry("Yeni Zelanda")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(154)
                .setCountryGroup("A")
                .setCountry("Yunanistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(155)
                .setCountryGroup("A")
                .setCountry("Zambiya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(156)
                .setCountryGroup("A")
                .setCountry("Zimbabve")
                .setVisaDuration(0)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(50))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(10))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(157)
                .setCountryGroup("B")
                .setCountry("Arnavutluk")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(158)
                .setCountryGroup("B")
                .setCountry("Filipinler")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(159)
                .setCountryGroup("B")
                .setCountry("İsrail")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(160)
                .setCountryGroup("B")
                .setCountry("Japonya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(161)
                .setCountryGroup("B")
                .setCountry("Kamboçya")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(162)
                .setCountryGroup("B")
                .setCountry("Makedoya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(163)
                .setCountryGroup("B")
                .setCountry("Mali")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(164)
                .setCountryGroup("B")
                .setCountry("Tacikistan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(165)
                .setCountryGroup("B")
                .setCountry("Umman")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(28))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(7))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(166)
                .setCountryGroup("C")
                .setCountry("Belçika")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(167)
                .setCountryGroup("C")
                .setCountry("Belarus")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(168)
                .setCountryGroup("C")
                .setCountry("Cezayir")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(169)
                .setCountryGroup("C")
                .setCountry("İspanya")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(170)
                .setCountryGroup("C")
                .setCountry("Kuveyt")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(171)
                .setCountryGroup("C")
                .setCountry("Lüksemburg")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(172)
                .setCountryGroup("C")
                .setCountry("Malta")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(173)
                .setCountryGroup("C")
                .setCountry("Singapur")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(174)
                .setCountryGroup("C")
                .setCountry("Tayvan")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(175)
                .setCountryGroup("C")
                .setCountry("Ürdün")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(18))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(5))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(176)
                .setCountryGroup("D")
                .setCountry("Etiyopya")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(14))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(3))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(177)
                .setCountryGroup("D")
                .setCountry("Güney Kore")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(14))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(3))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(178)
                .setCountryGroup("D")
                .setCountry("Hong Kong")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(14))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(3))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(179)
                .setCountryGroup("D")
                .setCountry("Mikronezya")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(14))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(3))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(180)
                .setCountryGroup("D")
                .setCountry("Rusya")
                .setVisaDuration(2)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(14))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(3))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(181)
                .setCountryGroup("E")
                .setCountry("Fas")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(10))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(1))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(182)
                .setCountryGroup("E")
                .setCountry("Fildişi Sahili")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(10))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(1))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(183)
                .setCountryGroup("E")
                .setCountry("Irak")
                .setVisaDuration(1)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(10))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(1))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(0.00)));
        list.add(new CountryDto()
                .setId(184)
                .setCountryGroup("E")
                .setCountry("Karadağ")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(10))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(1))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(185)
                .setCountryGroup("E")
                .setCountry("Mısır")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(10))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(1))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));
        list.add(new CountryDto()
                .setId(186)
                .setCountryGroup("E")
                .setCountry("Tunus")
                .setVisaDuration(3)
                .setFirstMonthPenaltyAmount(BigDecimal.valueOf(10))
                .setMonthlyPenaltyAmount(BigDecimal.valueOf(1))
                .setCardFee(BigDecimal.valueOf(160.00))
                .setVisaFee(BigDecimal.valueOf(1033.60)));

        return list;
    }
}
